thuehn/PowQuty

powqutyd/Makefile
powqutyd/files/Makefile
powqutyd/files/src/calculation.c
powqutyd/files/src/main.c
powqutyd/files/src/mqtt.c

Use config-submenu of powquty in menconfig to remove mosquitto from compilation.

add possibility to compile without mosquitto

---

powqutyd/Makefile
powqutyd/files/Makefile
powqutyd/files/etc/powqutyd.config
powqutyd/files/include/uci_config.h
powqutyd/files/src/calculation.c
powqutyd/files/src/main.c
powqutyd/files/src/mqtt.c
powqutyd/files/src/uci_config.c

Now uses /etc/config/powquty for configuration.

changed config to uci

---

luci-app-powquty/luasrc/controller/powquty/powquty.lua
luci-app-powquty/root/usr/bin/powquty-genconfig

-added h9 and h11 harmonics
-added avg,max,min to frequency and voltage
-enabled autoscaling of y-axis
-fixed harmonics graph by disabling stacked view

various graph adjustments in luci-app-powquty

---

luci-app-powquty/luasrc/model/cbi/powquty/powquty.lua
luci-app-powquty/root/usr/bin/powquty-genconfig
powqutyd/files/etc/powqutyd.config
powqutyd/files/include/helper.h
powqutyd/files/include/uci_config.h
powqutyd/files/src/calculation.c
powqutyd/files/src/helper.c
powqutyd/files/src/uci_config.c

change logfile location with 'powquty_path' in /etc/config/powquty
default location is set to /tmp/powquty.log

make logfile location configurable via uci

---

powqutyd/files/src/helper.c

This will add the ability to check if a file exceeds a given file size

Add filesize check

---

powqutyd/files/src/helper.c

add leading zeros for constant line length in log file

---

powqutyd/files/src/helper.c

set output length to correct values (%010.6f -> voltage, %09.6f -> frequency)

Fix output format

---

luci-app-powquty/luasrc/controller/powquty/powquty.lua

-added 10min timerange
-added units to avg/max/min

luci-app adjustments

---

luci-app-powquty/luasrc/controller/powquty/powquty.lua
luci-app-powquty/luasrc/view/powquty/graph.htm

-autorefresh in powquty graph no longer produces incomplete images
-capitalized spelling of PowQuty in luci-app

luci-app-powquty: fixed incomplete loading of images

---

README.md

Update contributor section

---

powqutyd/files/Makefile
powqutyd/files/include/calculation.h
powqutyd/files/include/event_handling.h
powqutyd/files/src/calculation.c
powqutyd/files/src/event_handling.c

This is the foundation for any notifications to be send

Add event handling basics

---

powqutyd/files/src/event_handling.c

Add the local time to powqutyd notifications
The new slack notifications will look like
Voltage dip >= 10% started: 2017-07-08 11:02:36

Add local time

---

luci-app-powquty/luasrc/model/cbi/powquty/powquty.lua
powqutyd/files/Makefile
powqutyd/files/etc/powqutyd.config
powqutyd/files/include/mqtt.h
powqutyd/files/include/uci_config.h
powqutyd/files/src/event_handling.c
powqutyd/files/src/mqtt.c
powqutyd/files/src/uci_config.c

Inform user via mqtt about powquty events. 
The structure is 
DEV UUID, Event, Timestamp
BERTUB001,Voltage dip < 10%,1499556605,1748
If the appearance of events is to close to each other mqtt can not notify the user
at the moment.

Add mqtt events

---

powqutyd/files/src/calculation.c

Add missing if condition to run powquty without input file

---

powqutyd/files/src/event_handling.c

Add missing file close

---

powqutyd/files/src/main.c

Stop_mosquitto only if we use it

---

luci-app-powquty/luasrc/model/cbi/powquty/powquty.lua

Add requested user interface additions
<li>latitude</li>
<li>longitude</li>
<li>mqtt server username</li>
<li>mqtt password</li>

Add to webconfig

---

luci-app-powquty/luasrc/controller/powquty/powquty.lua
luci-app-powquty/luasrc/view/powquty/event.htm

Improve the front-end usability and stop site complete reload. 
The upper table refreshes now every 5 seconds. The log file content is
only refreshed on button click. This button reloads the complete webpage

Frontend update

---

luci-app-powquty/Makefile
luci-app-powquty/luasrc/controller/powquty/powquty.lua
luci-app-powquty/luasrc/view/powquty/event.htm

Change unit for time measurement to ms

---

README.md

Fix some typos and replace LEDE with OpenWrt

---

measurement-scripts/powcrond

e.g., crashed/not running, output timeout
Signed-off-by: Benjamin Vahl <benjamin.vahl@dai-labor.de>

powcrond script auto-restarts powqutyd on failure

---

powqutyd/Makefile
powqutyd/files/src/helper.c

Fix memory leak

---

powqutyd/files/src/calculation.c
powqutyd/files/src/helper.c

If we want to keep the scope of variables small feel free to ignore the second commit.

Minor fixes

---

powqutyd/files/src/mqtt.c

Remove second T1012 value from mqtt message

---

powqutyd/files/src/mqtt.c

Use correct value for t1012 data

---

powqutyd/files/src/mqtt.c

Change pkg json type

---

luci-app-powquty/luasrc/controller/powquty/powquty.lua
luci-app-powquty/root/usr/bin/powquty-genconfig

Needed adjustment to new uci api
Signed-off-by: Tobias Ilte <tobias.ilte@campus.tu-berlin.de>

Fixes collectd-config not being generated

---

README.md
powqutyd/files/Makefile
powqutyd/files/include/file_checks.h
powqutyd/files/include/file_handling.h
powqutyd/files/include/helper.h
powqutyd/files/include/raw_dump.h
powqutyd/files/include/uci_config.h
powqutyd/files/src/file_checks.c
powqutyd/files/src/file_handling.c
powqutyd/files/src/helper.c
powqutyd/files/src/main.c
powqutyd/files/src/mqtt.c
powqutyd/files/src/raw_dump.c
powqutyd/files/src/retrieval.c
powqutyd/files/src/uci_config.c

To dump raw powquty output to a file powqutyd has to be started with
```powqutyd --rawfile <Path/to/file>```
Normal powquty output will be written to stdout, while raw content will
be written to the file provided
This PR also contains some minor clean ups and fixes for Warnings.

Dump raw to file

---

measurement-scripts/wesense_connect.sh
measurement-scripts/wesense_connect2.sh

Add wesense detection script

---

powqutyd/files/src/event_handling.c
powqutyd/files/src/raw_dump.c

Cleanup code & remove flag from raw

Cleanup raw file

---

powqutyd/files/src/raw_dump.c

This pull request adds two things
1. Move memory allocation to a separate function and check if memory could be allocated
2. Free allocated memory on thread stop

Free memory after usage and add checks

---

powqutyd/files/include/raw_dump.h
powqutyd/files/src/calculation.c
powqutyd/files/src/raw_dump.c
powqutyd/files/src/retrieval.c

Working state, does compile, but not

[working state]Reformat raw dump

---

powqutyd/files/include/event_handling.h
powqutyd/files/include/raw_dump.h
powqutyd/files/include/retrieval.h
powqutyd/files/src/calculation.c
powqutyd/files/src/event_handling.c
powqutyd/files/src/main.c
powqutyd/files/src/mqtt.c
powqutyd/files/src/raw_dump.c
powqutyd/files/src/retrieval.c

This pull request contains:
Bugfixes
Fix for a possible memory leak in eventhandling subroutine
Write calculated voltage samples to raw log

Raw sample improvements

---

powqutyd/files/include/event_handling.h
powqutyd/files/include/file_handling.h
powqutyd/files/include/retrieval.h
powqutyd/files/src/calculation.c
powqutyd/files/src/event_handling.c
powqutyd/files/src/file_handling.c
powqutyd/files/src/helper.c
powqutyd/files/src/main.c
powqutyd/files/src/mqtt.c
powqutyd/files/src/raw_dump.c
powqutyd/files/src/retrieval.c

This commit concludes the changes done on the raw log branch.
It includes changes to the raw log file, coding
style changes and some possible memory leak fixes.
For more details check the commit messages below.
These commits where done be three contributors:
Commit 6 by thuehn
Commit 5 by nadim-el-sayed
Rest by ikstream
Add return value checks for allocated memory
(cherry picked from commit 4827102266b6c3c540f9665c8f7f8bcc1f3cc077)
Free allocated memory in raw dump on stopping thread
(cherry picked from commit 66e56c02fae5565c6a80e82abcdb257f1ef92975)
Add offset and scaling_factor to raw dump
(cherry picked from commit …

Bring raw log branch to master
